export * as authService from "./authService.js"
export * as doctorService from "./doctorService.js"
export * as patientService from "./patientService.js"
export * as queries from "../repositories/index.js"
export * as schemas from "../schemas/index.js"
